In [2]:
##pandas used for data  analysis and c;eaning


pip install pandas

SyntaxError: invalid syntax (331713640.py, line 4)

In [3]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Chitranshi Pandey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Chitranshi Pandey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Chitranshi Pandey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\Chitranshi Pandey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 1.5 MB/s eta 0:00:07
   ---- ----------------------------------- 1.0/9.9 MB 1.5 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/9.9 MB 1.7 MB/s eta 0:00:06
   ------- -------------------------------- 1.8/9.9 MB 1.7 MB/s eta 0:00:05
   -------- ------------------------------- 2.1/9.9 MB 1.8 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.9 MB 1.7 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.9 MB 1.7 MB/s eta 0:00:05
   ---------- ----------------------------- 2.6/9.9 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.9 MB 1.3 MB/s eta 0:00:06
   ------------ --------------------------- 3.1/9.9 MB 1.4 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.9 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.3 MB/s eta 0:00:05
   --------------- ------------------------ 3.9/9.9 MB 1.1 MB/s eta 0:00:06
   --------------- ------------------------ 3.9/9.9 MB 1.1 MB/s eta 0:00:06
   ----------------- ---------------------- 4.2/9.9 MB 1.0 MB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.9 MB 1.1 MB/s eta 0:00:06
   ------------------- -------------------- 4.7/9.9 MB 1.1 MB/s eta 0:00:05
   -------------------- ------------------- 5.0/9.9 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.9 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.9 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.9 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.9 MB 1.0 MB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.9 MB 1.0 MB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.9 MB 1.0 MB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.9 MB 1.0 MB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 1.1 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.1 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.0 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.0 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.0 MB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 994.7 kB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 994.7 kB/s eta 0:00:03
   ------------------------------- -------- 7.9/9.9 MB 973.9 kB/s eta 0:00:03
   -------------------------------- ------- 8.1/9.9 MB 961.0 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 961.0 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 942.9 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 942.9 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 931.5 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 931.5 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 931.5 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 912.3 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 912.3 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 894.7 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 899.9 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 899.9 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 899.9 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 881.1 kB/s  0:00:11
Installing collected packages: pandas
Successfully installed pandas-3.0.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [ ]:
##pandas ke do datastructures hote h ek series(1D) and dataframes(2D)--
#pandas is a libarary used for data maipulation , cleaing , analysis and transfromation

In [9]:
##series 

import pandas as pd

data  = {'a':12}
series = pd.Series(data,)
print(series)

a    12
dtype: int64

In [6]:
data = {'a':1,'b':2,'c':3}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index = [1,2,3]
pd.Series(data,index)

1    10
2    20
3    30
dtype: int64

In [31]:
##datraframes

data ={
    'name':['chitra','sania','nuikhi'],
    'age':[25,34,45],
    'city':['banglore','delhit','texas']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

     name  age      city
0  chitra   25  banglore
1   sania   34    delhit
2  nuikhi   45     texas
<class 'pandas.DataFrame'>

In [17]:
##create a dat frmaer from a list of disctotires
##DATAFRAMES------ye 2D table hoti hai,sql jaise table
# 0,1,2 row ka index hota hai name,age city column haihar columm ka alga type ho sakta hai


data = [
    {'name':'chitanshi','age':34,'city':'delhi'},
    {'name':'chita','age':14,'city':'up'},
    {'name':'chiti','age':40,'city':'luicknow'},

]

fd = pd.DataFrame(data)
print(fd)

print(fd['name']) #name ka pura column agaya
#3row accesing
#fd.iloc[0]
fd.iloc[1:3]['age']  #----row slicing

        name  age      city
0  chitanshi   34     delhi
1      chita   14        up
2      chiti   40  luicknow
0    chitanshi
1        chita
2        chiti
Name: name, dtype: str

1    14
2    40
Name: age, dtype: int64

In [ ]:
##important properties of datafrmaes
#df.shape(row,columns) -- 
#df.column ---- column names
#df.head -- first five rows
#df.tail --last 5 rows
#column accesing

In [ ]:

#for csv file
df = pd.read_csv('Students data.csv')
df.head(5) ##for first five row

,ID,class,gender,race,GPA,Algebra,Calculus1,Calculus2,Statistics,Probability,Measure,Functional_analysis,from1,from2,from3,from4,y
0,1141,A,male,1,73.47,64,81,87,60,74,71,60,A,A,A,3,0
1,1142,A,female,1,71.22,57,50,51,51,55,62,61,B,A,A,2,0
2,1143,A,female,2,74.56,47,48,71,60,61,68,64,C,A,A,0,1
3,1144,A,female,1,72.89,46,72,38,60,29,54,51,D,A,A,0,0
4,1145,A,female,1,70.11,49,45,63,60,66,66,61,E,A,A,0,0

In [57]:
##accesing data from dtaa frames
data

[{'name': 'chitanshi', 'age': 34, 'city': 'delhi'},
 {'name': 'chita', 'age': 14, 'city': 'up'},
 {'name': 'chiti', 'age': 40, 'city': 'luicknow'}]

In [58]:
fd

        name  age      city
0  chitanshi   34     delhi
1      chita   14        up
2      chiti   40  luicknow

In [59]:
print(type(fd))

<class 'pandas.DataFrame'>

In [60]:
fd.iloc[0] ##zeroth row dega

name    chitanshi
age            34
city        delhi
Name: 0, dtype: object

In [61]:
fd['name']
##type(fd['name'])

0    chitanshi
1        chita
2        chiti
Name: name, dtype: str

In [64]:
fd.iloc[1]['name'] ##zero row ka name dedo

'chita'

In [63]:
fd.iloc[0:3]['name']

0    chitanshi
1        chita
2        chiti
Name: name, dtype: str

In [66]:
fd.iloc[0][1:2]

age    34
Name: 0, dtype: object

In [70]:
fd

        name  age      city
0  chitanshi   34     delhi
1      chita   14        up
2      chiti   40  luicknow

In [ ]:
##accesing a specified index

fd.at[1,'age'] ##roe ka index and column ka name
b

np.int64(14)

In [ ]:
fd.iat[2,2] ##row index column index

'luicknow'

In [72]:
fd

        name  age      city
0  chitanshi   34     delhi
1      chita   14        up
2      chiti   40  luicknow

In [ ]:
#3data manipulation with dataframes

fd['salary'] = [5000,6000,70000] ##adding a column
fd

        name  age      city  salary
0  chitanshi   34     delhi    5000
1      chita   14        up    6000
2      chiti   40  luicknow   70000

In [80]:
##remove a colun
fd.drop('salary',axis=1,inplace=True)  ##for checking column wise coz in deafultit chekcs row wise

KeyError: "['salary'] not found in axis"

In [19]:
##add age to the cvolumm
fd['age']=fd['age']+1

fd

        name  age      city
0  chitanshi   36     delhi
1      chita   16        up
2      chiti   42  luicknow

In [20]:
df.drop(0,inplace=True) ##the changes are not permannent to make it permannt we use inplace = true

NameError: name 'df' is not defined

In [93]:
fd

        name  age      city
0  chitanshi   35     delhi
1      chita   15        up
2      chiti   41  luicknow

In [ ]:
##daat manipulation ans anualysis with pandas

In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('Studentsdata.csv')
print(df)

df = pd.read_csv("xnmbs")
print(df)

       ID class  gender  race    GPA  Algebra  Calculus1  Calculus2  \
0    1141     A    male     1  73.47       64         81         87
1    1142     A  female     1  71.22       57         50         51
2    1143     A  female     2  74.56       47         48         71
3    1144     A  female     1  72.89       46         72         38
4    1145     A  female     1  70.11       49         45         63
..    ...   ...     ...   ...    ...      ...        ...        ...
100  1241     A  female     1  88.34       87         83         92
101  1242     B    male     1  89.84       98         77         95
102  1243     B    male     1  88.82       83         80         91
103  1244     A    male     1  86.60       92         82         91
104  1245     A    male     1  93.71       93         97         99

     Statistics  Probability  Measure  Functional_analysis from1 from2 from3  \
0            60           74       71                   60     A     A     A
1            51           55       62                   61     B     A     A
2            60           61       68                   64     C     A     A
3            60           29       54                   51     D     A     A
4            60           66       66                   61     E     A     A
..          ...          ...      ...                  ...   ...   ...   ...
100          98           93       86                   90     M     B     A
101          98           96       88                  100     A     B     A
102          98           93       95                   71     T     B     A
103          99           94       82                   78     S     B     A
104         100           97       90                   90     K     B     A

     from4  y
0        3  0
1        2  0
2        0  1
3        0  0
4        0  0
..     ... ..
100      0  1
101      0  1
102      0  2
103      0  2
104      0  2

[105 rows x 17 columns]

In [ ]:
df.tail(5) ## last ki panch row

,ID,class,gender,race,GPA,Algebra,Calculus1,Calculus2,Statistics,Probability,Measure,Functional_analysis,from1,from2,from3,from4,y
100,1241,A,female,1,88.34,87,83,92,98,93,86,90,M,B,A,0,1
101,1242,B,male,1,89.84,98,77,95,98,96,88,100,A,B,A,0,1
102,1243,B,male,1,88.82,83,80,91,98,93,95,71,T,B,A,0,2
103,1244,A,male,1,86.60,92,82,91,99,94,82,78,S,B,A,0,2
104,1245,A,male,1,93.71,93,97,99,100,97,90,90,K,B,A,0,2

In [ ]:
df.describe() ##statical data deta hai --min,mean,count,max, avg data ka short report card

,ID,race,GPA,Algebra,Calculus1,Calculus2,Statistics,Probability,Measure,Functional_analysis,from4,y
count,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000,105.000000
mean,1193.000000,1.790476,82.957048,76.057143,71.961905,78.942857,85.133333,83.876190,80.761905,75.323810,0.504762,0.714286
std,30.454885,1.673867,6.053187,11.722618,12.197039,14.997326,10.269509,10.514363,10.296119,13.003324,0.889293,0.828742
min,1141.000000,1.000000,63.490000,46.000000,38.000000,17.000000,51.000000,29.000000,54.000000,9.000000,0.000000,0.000000
25%,1167.000000,1.000000,79.340000,67.000000,64.000000,71.000000,80.000000,79.000000,74.000000,67.000000,0.000000,0.000000
50%,1193.000000,1.000000,84.110000,76.000000,73.000000,83.000000,87.000000,85.000000,81.000000,76.000000,0.000000,0.000000
75%,1219.000000,1.000000,87.300000,84.000000,80.000000,91.000000,92.000000,92.000000,89.000000,85.000000,0.000000,1.000000
max,1245.000000,7.000000,93.710000,98.000000,100.000000,99.000000,100.000000,97.000000,100.000000,100.000000,3.000000,2.000000

In [ ]:
df.dtypes  #--dataframe ke har column ka data type batat hai

ID                       int64
class                      str
gender                     str
race                     int64
GPA                    float64
Algebra                  int64
Calculus1                int64
Calculus2                int64
Statistics               int64
Probability              int64
Measure                  int64
Functional_analysis      int64
from1                      str
from2                      str
from3                      str
from4                    int64
y                        int64
dtype: object

In [ ]:
##handling missing value -- 
#df.isnull()--dataframe maia jaha bbi missing h wahaa true deta hai
#df.isnull().any() --agar coulumn mai kam se kam ek bhi missing value h toh true or bilkul missing nhi h toh false
df.isnull().any(axis=1)  #axxis = 0  mtln column wise check karna or axis = 1 mtln row wise chekc karna default bhi axis = 0 hota hai
##df.isnull().sum() #3true ko one manta hai or false ko zero or uska sum kr deta hai

0      False
1      False
2      False
3      False
4      False
       ...
100    False
101    False
102    False
103    False
104    False
Length: 105, dtype: bool

In [ ]:
df.fillna(1) ## jaha bhi mising ya naa h waha fill kardo in this cas ejha bhi naan h eaha 1 daaldo

,ID,class,gender,race,GPA,Algebra,Calculus1,Calculus2,Statistics,Probability,Measure,Functional_analysis,from1,from2,from3,from4,y
0,1141,A,male,1,73.47,64,81,87,60,74,71,60,A,A,A,3,0
1,1142,A,female,1,71.22,57,50,51,51,55,62,61,B,A,A,2,0
2,1143,A,female,2,74.56,47,48,71,60,61,68,64,C,A,A,0,1
3,1144,A,female,1,72.89,46,72,38,60,29,54,51,D,A,A,0,0
4,1145,A,female,1,70.11,49,45,63,60,66,66,61,E,A,A,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1241,A,female,1,88.34,87,83,92,98,93,86,90,M,B,A,0,1
101,1242,B,male,1,89.84,98,77,95,98,96,88,100,A,B,A,0,1
102,1243,B,male,1,88.82,83,80,91,98,93,95,71,T,B,A,0,2
103,1244,A,male,1,86.60,92,82,91,99,94,82,78,S,B,A,0,2
104,1245,A,male,1,93.71,93,97,99,100,97,90,90,K,B,A,0,2

In [ ]:
##filing misisn values with mean of the columns--chatgpt se padhana
df['sales_fill'] = df['Algebra'].fillna(df['Algebra'].mean()) ##algebra mai jaop or jaha bhi null h waha mean daldo or ek naya column bnrah data dalne ke liye
df

,ID,class,gender,race,GPA,Algebra,Calculus1,Calculus2,Statistics,Probability,Measure,Functional_analysis,from1,from2,from3,from4,y,sales_fill
0,1141,A,male,1,73.47,64,81,87,60,74,71,60,A,A,A,3,0,64
1,1142,A,female,1,71.22,57,50,51,51,55,62,61,B,A,A,2,0,57
2,1143,A,female,2,74.56,47,48,71,60,61,68,64,C,A,A,0,1,47
3,1144,A,female,1,72.89,46,72,38,60,29,54,51,D,A,A,0,0,46
4,1145,A,female,1,70.11,49,45,63,60,66,66,61,E,A,A,0,0,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1241,A,female,1,88.34,87,83,92,98,93,86,90,M,B,A,0,1,87
101,1242,B,male,1,89.84,98,77,95,98,96,88,100,A,B,A,0,1,98
102,1243,B,male,1,88.82,83,80,91,98,93,95,71,T,B,A,0,2,83
103,1244,A,male,1,86.60,92,82,91,99,94,82,78,S,B,A,0,2,92
104,1245,A,male,1,93.71,93,97,99,100,97,90,90,K,B,A,0,2,93

In [ ]:
##remainh coloums --pandas ka function h jo row and coloumn ka name change karta hai purana name dete hai or name dete hai
df=df.rename(columns={'Algebra':'Awe'}) 
df

,ID,class,gender,race,GPA,Awe,Calculus1,Calculus2,Statistics,Probability,Measure,Functional_analysis,from1,from2,from3,from4,y,sales_fill
0,1141,A,male,1,73.47,64,81,87,60,74,71,60,A,A,A,3,0,64
1,1142,A,female,1,71.22,57,50,51,51,55,62,61,B,A,A,2,0,57
2,1143,A,female,2,74.56,47,48,71,60,61,68,64,C,A,A,0,1,47
3,1144,A,female,1,72.89,46,72,38,60,29,54,51,D,A,A,0,0,46
4,1145,A,female,1,70.11,49,45,63,60,66,66,61,E,A,A,0,0,49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1241,A,female,1,88.34,87,83,92,98,93,86,90,M,B,A,0,1,87
101,1242,B,male,1,89.84,98,77,95,98,96,88,100,A,B,A,0,1,98
102,1243,B,male,1,88.82,83,80,91,98,93,95,71,T,B,A,0,2,83
103,1244,A,male,1,86.60,92,82,91,99,94,82,78,S,B,A,0,2,92
104,1245,A,male,1,93.71,93,97,99,100,97,90,90,K,B,A,0,2,93

In [ ]:
##change datatypes
df['class_new'] = df['gender'].fillna(df['gender'].mean()).astype(int) ## ye female ka 0 leta h or male ka 1 or uska mean nikale ga or gendermai jaha bhi na hoga waha fill kar dega as int decimal ko int bana rahaa

TypeError: Cannot perform reduction 'mean' with string dtype

##expression in dataframes
df['New_value'] = df['race'].apply(lambda x:x*2)
df.head(5)

In [ ]:
##group da data on the basic of hign and mean of close
grouped_mean = df.groupby('gender')['Calculus1'].mean() ## gender ke basis ke gruops mai divide ,Ab har group ke andar sirf Calculus1 column select kar rahe ho.Ab har group ke Calculus1 marks ka average nikal rahe ho.
print(grouped_mean)

gender
female    70.529412
male      74.594595
Name: Calculus1, dtype: float64

In [ ]:
df['New_value'] = df['race'].apply(lambda x:x*2) ##race column select karke, apply mtln column ke har ek vakue par function lagagane  or naye column mai stor hoga

In [ ]:
####multiple groups --------komse colums group krne h ---kiske basis pe
# grouped_mean1 = df.groupby(['gender','race'])['Statistics'].sum() 
# print(grouped_mean1)
grouped_mean1 = df.groupby(['gender','race'])['Statistics'].agg(['mean','sum']) ##gander or race coulmn ke basis pe group karra h or un gruops ke liye statistics select kiya yaah do cheez nikal rha aha hai mean and sum
print(grouped_mean1)

                  mean   sum
gender race
female 1     86.500000  4844
       2     60.000000    60
       3     90.000000   180
       4     83.500000   167
       5     66.666667   200
       6     84.000000   168
       7     87.000000   174
male   1     86.360000  2159
       2     90.000000   180
       3     78.250000   313
       4     76.000000   152
       5     87.000000    87
       7     85.000000   255

In [32]:
## merging and joing dataframes
df1=pd.DataFrame({'key':['A','B','C'], 'vales1':[1,2,3]})
df2=pd.DataFrame({'key':['A','B','D'], 'vales1':[4,5,6]})

In [31]:
pd.merge(df1,df2,on="key",how="inner")

  key  vales1_x  vales1_y
0   A         1         4
1   B         2         5