In [2]:
##pandas used for data  analysis and c;eaning


pip install pandas

SyntaxError: invalid syntax (331713640.py, line 4)

In [3]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Chitranshi Pandey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Chitranshi Pandey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Chitranshi Pandey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\Users\Chitranshi Pandey\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 1.5 MB/s eta 0:00:07
   ---- ----------------------------------- 1.0/9.9 MB 1.5 MB/s eta 0:00:06
   ----- ---------------------------------- 1.3/9.9 MB 1.7 MB/s eta 0:00:06
   ------- -------------------------------- 1.8/9.9 MB 1.7 MB/s eta 0:00:05
   -------- ------------------------------- 2.1/9.9 MB 1.8 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.9 MB 1.7 MB/s eta 0:00:05
   --------- ------------------------------ 2.4/9.9 MB 1.7 MB/s eta 0:00:05
   ---------- ----------------------------- 2.6/9.9 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.9 MB 1.3 MB/s eta 0:00:06
   ------------ --------------------------- 3.1/9.9 MB 1.4 MB/s eta 0:00:05
   ------------- -------------------------- 3.4/9.9 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.3 MB/s eta 0:00:05
   -------------- ------------------------- 3.7/9.9 MB 1.3 MB/s eta 0:00:05
   --------------- ------------------------ 3.9/9.9 MB 1.1 MB/s eta 0:00:06
   --------------- ------------------------ 3.9/9.9 MB 1.1 MB/s eta 0:00:06
   ----------------- ---------------------- 4.2/9.9 MB 1.0 MB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.9 MB 1.1 MB/s eta 0:00:06
   ------------------- -------------------- 4.7/9.9 MB 1.1 MB/s eta 0:00:05
   -------------------- ------------------- 5.0/9.9 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.9 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.9 MB 1.1 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.9 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.9 MB 1.0 MB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.9 MB 1.0 MB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.9 MB 1.0 MB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.9 MB 1.0 MB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 1.0 MB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 1.1 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.1 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.1 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.0 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.0 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.0 MB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 994.7 kB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 994.7 kB/s eta 0:00:03
   ------------------------------- -------- 7.9/9.9 MB 973.9 kB/s eta 0:00:03
   -------------------------------- ------- 8.1/9.9 MB 961.0 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 961.0 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 942.9 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 942.9 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 931.5 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 931.5 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 931.5 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 912.3 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 912.3 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 894.7 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 899.9 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 899.9 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 899.9 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 881.1 kB/s  0:00:11
Installing collected packages: pandas
Successfully installed pandas-3.0.0
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

In [5]:
##series 

import pandas as pd

data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
data = {'a':1,'b':2,'c':3}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

In [7]:
data = [10,20,30]
index = [1,2,3]
pd.Series(data,index=index)

1    10
2    20
3    30
dtype: int64

In [31]:
##datraframes

data ={
    'name':['chitra','sania','nuikhi'],
    'age':[25,34,45],
    'city':['banglore','delhit','texas']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

     name  age      city
0  chitra   25  banglore
1   sania   34    delhit
2  nuikhi   45     texas
<class 'pandas.DataFrame'>

In [90]:
##create a dat frmaer from a list of disctotires


data = [
    {'name':'chitanshi','age':34,'city':'delhi'},
    {'name':'chita','age':14,'city':'up'},
    {'name':'chiti','age':40,'city':'luicknow'},

]

fd = pd.DataFrame(data)
print(fd)

        name  age      city
0  chitanshi   34     delhi
1      chita   14        up
2      chiti   40  luicknow

In [ ]:

#for csv file
df = pd.read_csv('Students data.csv')
df.head(5) ##for first five row

,ID,class,gender,race,GPA,Algebra,Calculus1,Calculus2,Statistics,Probability,Measure,Functional_analysis,from1,from2,from3,from4,y
0,1141,A,male,1,73.47,64,81,87,60,74,71,60,A,A,A,3,0
1,1142,A,female,1,71.22,57,50,51,51,55,62,61,B,A,A,2,0
2,1143,A,female,2,74.56,47,48,71,60,61,68,64,C,A,A,0,1
3,1144,A,female,1,72.89,46,72,38,60,29,54,51,D,A,A,0,0
4,1145,A,female,1,70.11,49,45,63,60,66,66,61,E,A,A,0,0

In [57]:
##accesing data from dtaa frames
data

[{'name': 'chitanshi', 'age': 34, 'city': 'delhi'},
 {'name': 'chita', 'age': 14, 'city': 'up'},
 {'name': 'chiti', 'age': 40, 'city': 'luicknow'}]

In [58]:
fd

        name  age      city
0  chitanshi   34     delhi
1      chita   14        up
2      chiti   40  luicknow

In [59]:
print(type(fd))

<class 'pandas.DataFrame'>

In [60]:
fd.iloc[0] ##zeroth row dega

name    chitanshi
age            34
city        delhi
Name: 0, dtype: object

In [61]:
fd['name']
##type(fd['name'])

0    chitanshi
1        chita
2        chiti
Name: name, dtype: str

In [64]:
fd.iloc[1]['name'] ##zero row ka name dedo

'chita'

In [63]:
fd.iloc[0:3]['name']

0    chitanshi
1        chita
2        chiti
Name: name, dtype: str

In [66]:
fd.iloc[0][1:2]

age    34
Name: 0, dtype: object

In [70]:
fd

        name  age      city
0  chitanshi   34     delhi
1      chita   14        up
2      chiti   40  luicknow

In [ ]:
##accesing a specified index

fd.at[1,'age'] ##roe ka index and column ka name

np.int64(14)

In [ ]:
fd.iat[2,2] ##row index column index

'luicknow'

In [72]:
fd

        name  age      city
0  chitanshi   34     delhi
1      chita   14        up
2      chiti   40  luicknow

In [ ]:
#3data manipulation with dataframes

fd['salary'] = [5000,6000,70000] ##adding a column
fd

        name  age      city  salary
0  chitanshi   34     delhi    5000
1      chita   14        up    6000
2      chiti   40  luicknow   70000

In [80]:
##remove a colun
fd.drop('salary',axis=1,inplace=True)  ##for checking column wise coz in deafultit chekcs row wise

KeyError: "['salary'] not found in axis"

In [91]:
##add age to the cvolumm
fd['age']=fd['age']+1

fd

        name  age      city
0  chitanshi   35     delhi
1      chita   15        up
2      chiti   41  luicknow

In [92]:
df.drop(0,inplace=True) ##the changes are not permannent to make it permannt we use inplace = true

KeyError: '[0] not found in axis'

In [93]:
fd

        name  age      city
0  chitanshi   35     delhi
1      chita   15        up
2      chiti   41  luicknow